### ISSUE TITLE
Error when making table in qmd

### ISSUE THREAD

**Issue by martinig** [martinig/Fitness-and-dispersal-MA#17]
@itchyshin 

Example chunk of code:

```
#| eval: false

tab_class <- all_models(mod_class,  mod = "species_class", type = "normal")

# saving tab_class as RDS
saveRDS(tab_class, here("Rdata", "tab_class.RDS"))   
```

When I ignore the eval: false bit and run tab_class, I get this error:

```
tab_class <- all_models(mod_class,  mod = "species_class", type = "normal")
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `relevel.default()`:
! 'relevel' only for (unordered) factors
Run `rlang::last_trace()` to see where the error occurred.
Warning messages:
1: The var-cov matrix appears to be not positive definite in cluster N. 
2: The var-cov matrix appears to be not positive definite in cluster E. 
3: The var-cov matrix appears to be not positive definite in cluster C. 
```

This is happening for all tables now, but it is worth checking especially for:
- [x] line 1180 (study duration moderator as it is a numerical moderator instead of factor)
- [x] line 1527 (first interaction moderator)

**Comment by itchyshin** [comment]
all fixed - @martinig

**Comment by martinig** [comment]
Some errors are still persisting. I will include them below.

**Comment by martinig** [comment]
Line 753.

tab_class <- all_models(mod_class,  mod = "species_class", type = "normal")
There were 20 warnings (use warnings() to see them)
> 
> warnings()
Warning messages:
1: The var-cov matrix appears to be not positive definite in cluster N.
2: The var-cov matrix appears to be not positive definite in cluster E.
3: The var-cov matrix appears to be not positive definite in cluster C.
4: The var-cov matrix appears to be not positive definite in cluster N.
5: The var-cov matrix appears to be not positive definite in cluster E.
6: The var-cov matrix appears to be not positive definite in cluster C.
7: The var-cov matrix appears to be not positive definite in cluster N.
8: The var-cov matrix appears to be not positive definite in cluster E.
9: The var-cov matrix appears to be not positive definite in cluster C.
10: The var-cov matrix appears to be not positive definite in cluster N.
11: The var-cov matrix appears to be not positive definite in cluster E.
12: The var-cov matrix appears to be not positive definite in cluster C.
13: The var-cov matrix appears to be not positive definite in cluster N.
14: The var-cov matrix appears to be not positive definite in cluster E.
15: The var-cov matrix appears to be not positive definite in cluster C.
16: In min(x$ddf[bn0]) : no non-missing arguments to min; returning Inf
17: In min(x$ddf[bn0]) : no non-missing arguments to min; returning Inf
18: In min(x$ddf[bn0]) : no non-missing arguments to min; returning Inf
19: In min(x$ddf[bn0]) : no non-missing arguments to min; returning Inf
20: In min(x$ddf[bn0]) : no non-missing arguments to min; returning Inf

**Comment by itchyshin** [comment]
@martinig these are fine. These are warnings not errors.

**Comment by martinig** [comment]
Great! I won't worry about these in that case.
